import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    absolute: 'Elisa',
    default: 'Nest.js Tutorial',
    template: '%s | Nest.js Tutorial',
  },
  description: "Generated by create next app",
};

const styleMe = {
        backgroundColor: 'lightblue',
        padding: '2rem',
    }
export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <header style={styleMe}>
            <p>Header</p>
        </header>
        <main className="grow">
            {children}
        </main>
        
        <footer style={styleMe}>
            <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
